CREATE TABLE symbols
(
    id                     SERIAL PRIMARY KEY,
    symbol                 VARCHAR,
    company_name            VARCHAR,
    primary_exchange        VARCHAR,
    calculation_price       VARCHAR,
    open                   DOUBLE PRECISION,
    open_time               BIGINT,
    open_source             VARCHAR,
    close                  DOUBLE PRECISION,
    close_time              BIGINT,
    close_source            VARCHAR,
    high                   DOUBLE PRECISION,
    high_time               DOUBLE PRECISION,
    high_source             VARCHAR,
    low                    DOUBLE PRECISION,
    low_time                BIGINT,
    low_source              VARCHAR,
    latest_price            DOUBLE PRECISION,
    latest_source           VARCHAR,
    latest_time             VARCHAR,
    latest_update           BIGINT,
    latest_volume           BIGINT,
    iex_realtime_price       DOUBLE PRECISION,
    iex_realtime_size        BIGINT,
    iex_last_updated         BIGINT,
    delayed_price           DOUBLE PRECISION,
    delayed_price_time       BIGINT,
    odd_lot_delayed_price     DOUBLE PRECISION,
    odd_lot_delayed_price_time BIGINT,
    extended_price          DOUBLE PRECISION,
    extended_change         DOUBLE PRECISION,
    extended_change_percent  DOUBLE PRECISION,
    extended_price_time      BIGINT,
    previous_close          DOUBLE PRECISION,
    previous_volume         BIGINT,
    change                 DOUBLE PRECISION,
    change_percent          DOUBLE PRECISION,
    volume                 DOUBLE PRECISION,
    iex_market_percent       DOUBLE PRECISION,
    iex_volume              BIGINT,
    avg_total_volume         BIGINT,
    iex_bid_price            DOUBLE PRECISION,
    iex_bid_size             BIGINT,
    iex_ask_price            DOUBLE PRECISION,
    iex_ask_size             BIGINT,
    iex_open                DOUBLE PRECISION,
    iex_open_time            BIGINT,
    iex_close               DOUBLE PRECISION,
    iex_close_time           BIGINT,
    market_cap              BIGINT,
    pe_ratio                DOUBLE PRECISION,
    week_52_high             DOUBLE PRECISION,
    week_52_low              DOUBLE PRECISION,
    ytd_change              DOUBLE PRECISION,
    last_trade_Time          BIGINT,
    is_us_market_open         BOOLEAN
)